### ISSUE TITLE
TO add company employee images in home page slider

### ISSUE THREAD

**Issue by R2904** [piyushpaliwal/nextjs-ambit#4]
![image](https://user-images.githubusercontent.com/75564199/209128810-b71b6252-f231-4856-b14f-6a3077f682b2.png)
to add employee images and it's yet to provide you by me.

**Comment by piyushpaliwal** [comment]
@R2904 by any chance do you have the images?

**Comment by R2904** [comment]
@piyushpaliwal we also will get that images in next 2 days.

**Comment by piyushpaliwal** [comment]
Won't do. The stock images look good
